//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracker.Web
{


    public partial class udfs
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new BugTracker.Web.LoggedIn Master
        {
            get
            {
                return ((BugTracker.Web.LoggedIn)(base.Master));
            }
        }
    }
}
